### ISSUE TITLE
1) User Can View App

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#1]
## 📢Details

- You will need to learn about using [font awesomes icons](https://fontawesome.com/v4.7.0/icons/). I have already added the CDN for you to use.

## 📂Wireframe

![user-can-view-app](https://user-images.githubusercontent.com/52118958/104825077-6e669300-580c-11eb-8616-e9d09c4f3481.png)

## 📃Task List

- [x] Build the navbar
   - [x] Populate with logo and font awesome icons (heart, cart)
   - [x] Style with css (background-color/positioning)
- [x] Build the main page
   - [x] Products header
   - [x] Products container
