### ISSUE TITLE
2) User Can View Products

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#2]
## 📢Details

- Take a look at the data.js file.  You will be rendering the products from that data model.

## 📂Wireframe

![user-can-view-products](https://user-images.githubusercontent.com/52118958/104825160-15e3c580-580d-11eb-8b9f-4ba0c082adb7.png)

## 📃Task List

- [x] Style the main product containers (positioning the big boxes/borders)
- [x] Style the contents of the containers
   - [x] Images (size/positioning)
   - [x] Name (positioning/fonts)
   - [x] Price (positioning/fonts)
   - [x] Font awesome icons (size/positioning)
      - [x] Mouseover styling
- [x] Populate the containers using data.js
   - [x] Define a function named render
   - [x] Iterate through through data model, and create DOM elements

**Comment by ejgilleland** [comment]
And immediately after looking at issue 3, I see that I should add an id attribute that takes the value of id referenced in data.products[index].id for the next issues. Oof!
