### ISSUE TITLE
3) User Can Favorite

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#3]
## 📢Details

- Take a look at the data.js file. You will be adding the users products into the favorites property.
- When the user clicks the heart icon, it will turn red.
- Don't worry about unfavoriting just yet

## 📂Wireframe

![user-can-favorite](https://user-images.githubusercontent.com/52118958/104825310-60654200-580d-11eb-881f-b3f0277fd836.png)

## 📃Task List

- [x] Use JS to listen for a click event on the heart icon
   - [x] Add the favorited product to the favorites property (push the corresponding product to the favorites array via callback function)
   - [x] Update the heart icon's styling (stay crimson to denote that it is active/added to favorites)

**Bonus:
 - [x] animation/transition styling for mouseclick on icon; hover is already styled.
