### ISSUE TITLE
4) User Can Add To Cart

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#4]
## 📢Details

- Take a look at the data.js file. You will be adding the users products into the cart property.
- When the user clicks the cart icon, it will turn blue.
- Don't worry about removing from cart just yet

## 📂Wireframe

![user-can-add-to-cart](https://user-images.githubusercontent.com/52118958/104825835-8559b500-580d-11eb-91fc-84275cf22ffb.png)

## 📃Task List

- [x] Use JS to listen for a click event on the cart icon
   - [x] Add the product to the cart property
   - [x] Update the cart icon's styling

**Bonus
 - [x] Some kind of animation/transition styling for mouseover and mouseclick on icon
