### ISSUE TITLE
5) User Can Unfavorite

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#5]
## 📢Details

- Take a look at the data.js file. You will be removing the users products from the favorites property.
- When the user clicks the heart icon of an already favorited product, it will turn back to black.

## 📂Wireframe

![user-can-unfavorite](https://user-images.githubusercontent.com/52118958/104826891-cfdb3180-580d-11eb-9b9c-ad5cf4449fc8.png)

## 📃Task List

- [x] Update the event listener to check favorited status
   - [x] If already favorited, then remove the product from the favorites property
   - [x] Change the heart styling back to black

**Bonus
 - [x] Some kind of animation/transition styling for mouseover and mouseclick on icon
