### ISSUE TITLE
6) User Can Remove from Cart

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#6]
## 📢Details

- Take a look at the data.js file. You will be removing the users products from the cart property.
- When the user clicks the cart icon of an already added product, it will turn back to black.

## 📂Wireframe

![user-can-remove-from-cart](https://user-images.githubusercontent.com/52118958/104826960-03b65700-580e-11eb-954c-fe3cba0e71e1.png)

## 📃Task List

- [ ] Update the event listener to check if product is in cart
   - [ ] If already in cart, then remove the product from the cart property (if not in cart, add to cart)
   - [ ] Change the cart styling back to black

**Bonus
 - [ ] Some kind of animation/transition styling for mouseover and mouseclick on icon
