### ISSUE TITLE
7) User Can View Favorites

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#7]
## 📢Details

- When the user clicks the heart icon in the header you will
   - Change the heading to favorites
   - Render only products that are favorited
   - If the user does not have any favorited products, you will display a message.  Something like: `No products avaliable`
   - If the user unfavorites something while on the favorites page, you will remove the product from the page

## 📂Wireframe

![user-can-view-favorites](https://user-images.githubusercontent.com/52118958/104827021-76273700-580e-11eb-9d2a-8e62aa6ff9d1.png)

## 📃Task List

Option 1:
   New page (favorites.html) that only displays favorited products, with same styling as index.html
   - [ ] Update the page if a favorite is removed (not quite sure how to implement this but that's what attempting it is for!)

Option 2 (more fun!! less practical!!):
   Stay on same page (index.html)
   - [ ] Update the text content of the header (change to Favorites)
   - [ ] Hide all products that are not in the favorite property
   - [ ] Update the page if a favorite is removed
