### ISSUE TITLE
8) User Can View Cart

### ISSUE THREAD

**Issue by shadorki** [ejgilleland/gundam-store#8]
## 📢Details

- When the user clicks the cart icon in the header you will
   - Change the heading to Cart
   - Render only products that are in the cart
   - Display the total of all the products in the cart
   - If the user does not have any products in their cart, you will display a message.  Something like: `Cart is empty`
   - If the user removes something from cart while on the cart page, you will remove the product from the page
   - If the user removes something from cart while on the cart page, you will update the total

## 📂Wireframe

![user-can-view-cart](https://user-images.githubusercontent.com/52118958/104827061-c900ee80-580e-11eb-8511-df63eaf5a0d4.png)

## 📃Task List

Option 1:
   New page (cart.html) that only displays favorited products, with same styling as index.html
   - [ ] Update the page if an item is removed from the cart (not quite sure how to implement this but that's what attempting it is for!)

Option 2 (more fun!!):
   Stay on same page (index.html)
   - [ ] Update the text content of the header (change to Cart)
   - [ ] Hide all products that are not in the cart property
   - [ ] Update the page if a product is removed from the cart
